In [1]:
#Import dependencies
import pandas as pd

In [3]:
#Read in cleaned CSV as DataFrame
delhi_df = pd.read_csv('delhi_weather_cleaned.csv')
delhi_df

,datetime_utc,conds,dewptm,fog,hail,hum,pressurem,rain,snow,tempm,thunder,tornado,vism,wdird,wdire,wspdm
0,19961101-11:00,Haze,9.0,0,0,27.0,1010.0,0,0,30.0,0,0,5.0,280.0,West,7.4
1,19961101-16:00,Haze,11.0,0,0,47.0,1011.0,0,0,23.0,0,0,1.2,0.0,North,0.0
2,19961101-18:00,Haze,13.0,0,0,60.0,1010.0,0,0,21.0,0,0,0.8,0.0,North,0.0
3,19961102-02:00,Haze,10.0,0,0,52.0,1011.0,0,0,20.0,0,0,2.0,200.0,SSW,9.3
4,19961102-03:00,Haze,10.0,0,0,46.0,1012.0,0,0,22.0,0,0,3.5,240.0,WSW,9.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80652,20170424-06:00,Haze,17.0,0,0,25.0,1005.0,0,0,34.0,0,0,4.0,320.0,NW,11.1
80653,20170424-09:00,Haze,14.0,0,0,16.0,1003.0,0,0,38.0,0,0,4.0,320.0,NW,22.2
80654,20170424-12:00,Haze,12.0,0,0,14.0,1002.0,0,0,36.0,0,0,4.0,270.0,West,18.5
80655,20170424-15:00,Haze,15.0,0,0,27.0,1004.0,0,0,32.0,0,0,2.0,320.0,NW,3.7
80656,20170424-18:00,Haze,15.0,0,0,30.0,1005.0,0,0,30.0,0,0,2.0,320.0,NW,3.7

In [10]:
#Creating the datetime/conds DataFrame
conds_df = delhi_df[['datetime_utc', 'conds']].set_index('datetime_utc')
conds_df

               conds
datetime_utc
19961101-11:00  Haze
19961101-16:00  Haze
19961101-18:00  Haze
19961102-02:00  Haze
19961102-03:00  Haze
...              ...
20170424-06:00  Haze
20170424-09:00  Haze
20170424-12:00  Haze
20170424-15:00  Haze
20170424-18:00  Haze

[80657 rows x 1 columns]

In [11]:
#Creating the features DataFrame
features_df = delhi_df[['datetime_utc', 'dewptm', 'fog', 'hail', 'hum', 'pressurem',
       'rain', 'snow', 'tempm', 'thunder', 'tornado', 'vism', 'wdird', 'wdire',
       'wspdm']].set_index('datetime_utc')
features_df

,dewptm,fog,hail,hum,pressurem,rain,snow,tempm,thunder,tornado,vism,wdird,wdire,wspdm
datetime_utc,,,,,,,,,,,,,,
19961101-11:00,9.0,0,0,27.0,1010.0,0,0,30.0,0,0,5.0,280.0,West,7.4
19961101-16:00,11.0,0,0,47.0,1011.0,0,0,23.0,0,0,1.2,0.0,North,0.0
19961101-18:00,13.0,0,0,60.0,1010.0,0,0,21.0,0,0,0.8,0.0,North,0.0
19961102-02:00,10.0,0,0,52.0,1011.0,0,0,20.0,0,0,2.0,200.0,SSW,9.3
19961102-03:00,10.0,0,0,46.0,1012.0,0,0,22.0,0,0,3.5,240.0,WSW,9.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20170424-06:00,17.0,0,0,25.0,1005.0,0,0,34.0,0,0,4.0,320.0,NW,11.1
20170424-09:00,14.0,0,0,16.0,1003.0,0,0,38.0,0,0,4.0,320.0,NW,22.2
20170424-12:00,12.0,0,0,14.0,1002.0,0,0,36.0,0,0,4.0,270.0,West,18.5
20170424-15:00,15.0,0,0,27.0,1004.0,0,0,32.0,0,0,2.0,320.0,NW,3.7
20170424-18:00,15.0,0,0,30.0,1005.0,0,0,30.0,0,0,2.0,320.0,NW,3.7

In [18]:
features_df.columns

Index(['dewptm', 'fog', 'hail', 'hum', 'pressurem', 'rain', 'snow', 'tempm',
       'thunder', 'tornado', 'vism', 'wdird', 'wdire', 'wspdm'],
      dtype='object')

In [20]:
#Exporting DataFrames as .csv files for exporting to delhi.db
conds_df.to_csv('Database/conds.csv',mode='w', header=False)
features_df.to_csv('Database/features.csv',mode='w', header=False)